// get student 

export const GET_STUDENT_PROGRESS="GET_STUDENT_PROGRESS"
export const GET_STUDENT_ERROR="GET_STUDENT_ERROR"
export const GET_STUDENT_SUCCESS="GET_STUDENT_SUCCESS"

// post student 


export const POST_STUDENT_PROGRESS="POST_STUDENT_PROGRESS"
export const POST_STUDENT_ERROR="POST_STUDENT_ERROR"
export const POST_STUDENT_SUCCESS="POST_STUDENT_SUCCESS"

// update 

export const UPDATE_STUDENT_PROGRESS="UPDATE_STUDENT_PROGRESS"
export const UPDATE_STUDENT_ERROR="UPDATE_STUDENT_ERROR"
export const UPDATE_STUDENT_SUCCESS="UPDATE_STUDENT_SUCCESS"

// delete 

export const DELETE_STUDENT_PROGRESS="DELETE_STUDENT_PROGRESS"
export const DELETE_STUDENT_ERROR="DELETE_STUDENT_ERROR"
export const DELETE_STUDENT_SUCCESS="DELETE_STUDENT_SUCCESS"