// get faculty 

export const GET_FACULTY_PROGRESS="GET_FACULTY_PROGRESS"
export const GET_FACULTY_SUCCESS="GET_FACULTY_SUCCESS"
export const GET_FACULTY_ERROR="GET_FACULTY_ERROR"

// post faculty 

export const POST_FACULTY_PROGRESS="POST_FACULTY_PROGRESS"
export const POST_FACULTY_SUCCESS="POST_FACULTY_SUCCESS"
export const POST_FACULTY_ERROR="POST_FACULTY_ERROR"

// delete faculty 

export const DELETE_FACULTY_PROGRESS="DELETE_FACULTY_PROGRESS"
export const DELETE_FACULTY_SUCCESS="DELETE_FACULTY_SUCCESS"
export const DELETE_FACULTY_ERROR="DELETE_FACULTY_ERROR"

// update faculty 

export const UPDATE_FACULTY_PROGRESS="UPDATE_FACULTY_PROGRESS"
export const UPDATE_FACULTY_SUCCESS="UPDATE_FACULTY_SUCCESS"
export const UPDATE_FACULTY_ERROR="UPDATE_FACULTY_ERROR"