// get the list of subadmin 

export const GET_SUBADMIN_LIST_PROGRESS = "GET_SUBADMIN_LIST_PROGRESS"
export const GET_SUBADMIN_LIST_SUCCESS = "GET_SUBADMIN_LIST_SUCCESS"
export const GET_SUBADMIN_LIST_ERROR = "GET_SUBADMIN_LIST_ERROR"

// create add or post subadmin 

export const POST_SUBADMIN_PROGRESS = "POST_SUBADMIN_PROGRESS"
export const POST_SUBADMIN_SUCCESS = "POST_SUBADMIN_SUCCESS"
export const POST_SUBADMIN_ERROR = "POST_SUBADMIN_ERROR"

// delete the subadmin 

export const DELETE_SUBADMIN_PROGRESS = "DELETE_SUBADMIN_PROGRESS"
export const DELETE_SUBADMIN_SUCCESS = "DELETE_SUBADMIN_SUCCESS"
export const DELETE_SUBADMIN_ERROR = "DELETE_SUBADMIN_ERROR"

// update the subadmin

export const UPDATE_SUBADMIN_PROGRESS = "UPDATE_SUBADMIN_PROGRESS"
export const UPDATE_SUBADMIN_SUCCESS = "UPDATE_SUBADMIN_SUCCESS"
export const UPDATE_SUBADMIN_ERROR = "UPDATE_SUBADMIN_ERROR"

